name:    hello-yesod
version: "0.0.0"

dependencies:
- base ^>= 4.15.1.0
- yesod ^>= 1.6.2
- yesod-core ^>= 1.6.23.1
- yesod-auth ^>= 1.6.11
- yesod-static ^>= 1.6.1.0
- yesod-form ^>= 1.7.0
- classy-prelude ^>= 1.5.0.2
- classy-prelude-conduit ^>= 1.5.0
- classy-prelude-yesod ^>= 1.5.0
- bytestring ^>= 0.10.12.1
- text ^>= 1.2.5.0
- persistent ^>= 2.13.3.5
- persistent-sqlite ^>= 2.13.1.0
- persistent-template ^>= 2.12.0.0
- template-haskell ^>= 2.17.0.0
- shakespeare ^>= 2.0.29
- hjsmin ^>= 0.2.0.4
- monad-control ^>= 1.0.3.1
- wai-extra ^>= 3.1.12.1
- yaml ^>= 0.11.8.0
- http-client-tls ^>= 0.3.6.1
- http-conduit ^>= 2.3.8
- directory ^>= 1.3.6.2
- warp ^>= 3.3.21
- data-default ^>= 0.7.1.1
- aeson ^>= 2.0.3.0
- conduit ^>= 1.3.4.2
- monad-logger ^>= 0.3.36
- fast-logger ^>= 3.1.1
- wai-logger ^>= 2.4.0
- file-embed ^>= 0.0.15.0
- safe ^>= 0.3.19
- unordered-containers ^>= 0.2.17.0
- containers ^>= 0.6.4.1
- vector ^>= 0.12.3.1
- time ^>= 1.9.3
- case-insensitive ^>= 1.2.1.0
- wai ^>= 3.2.3
- foreign-store ^>= 0.2

# The library contains all of our application code. The executable
# defined below is just a thin wrapper.
library:
  source-dirs: src
  when:
  - condition: (flag(dev)) || (flag(library-only))
    then:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O0
      cpp-options: -DDEVELOPMENT
    else:
      ghc-options:
      - -Wall
      - -fwarn-tabs
      - -O2

# Runnable executable for our application
executables:
  hello-yesod:
    main: main.hs
    source-dirs: app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hello-yesod
    when:
    - condition: flag(library-only)
      buildable: false

# Test suite
tests:
  hello-yesod-test:
    main: Spec.hs
    source-dirs: test
    ghc-options: -Wall
    dependencies:
    - hello-yesod
    - hspec >=2.0.0
    - yesod-test
    - microlens

# Define flags used by "yesod devel" to make compilation faster
flags:
  library-only:
    description: Build for use with "yesod devel"
    manual: false
    default: false
  dev:
    description: Turn on development settings, like auto-reload templates.
    manual: false
    default: false
